# -*- coding: utf-8 -*-
"""even or odd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T27evoYV-pXMsS8Hwp9R2-wzO2xxBWhw
"""

# Even or Odd Checker Program

def check_even_odd(number):
    if number % 2 == 0:
        return f"{number} is Even"
    else:
        return f"{number} is Odd"

def main():
    try:
        num = int(input("Enter a number: "))
        result = check_even_odd(num)
        print(result)
    except ValueError:
        print("Please enter a valid integer.")

if __name__ == "__main__":
    main()